# Generated by Django 4.0.6 on 2022-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=200, verbose_name='测试名称')),
                ('ttype', models.SmallIntegerField(choices=[(0, 'app'), (1, 'web')], verbose_name='测试类型')),
                ('subject', models.CharField(max_length=200, verbose_name='测试对象')),

            ],
            options={
                'verbose_name': '数据项目管理',
                'verbose_name_plural': '数据项目管理',
            },
        ),
    ]
