# Generated by Django 4.0.6 on 2022-07-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=200, verbose_name='测试名称')),
                ('ttype', models.SmallIntegerField(choices=[(0, 'app'), (1, 'web')], verbose_name='测试类型')),
                ('subject', models.CharField(max_length=200, verbose_name='测试对象')),
            ],
        ),
    ]
