# Generated by Django 4.0.6 on 2022-07-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_delete_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='测试对象')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.name')),
            ],
        ),
    ]
