# Generated by Django 4.0.6 on 2022-07-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taobao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('price', models.IntegerField(max_length=10, verbose_name='价格')),
                ('num', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name': 'taobao数据项目管理',
                'verbose_name_plural': 'taobao数据项目管理',
            },
        ),
    ]
